# Generated by Django 4.0 on 2026-06-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.TextField()),
                ('EventDate', models.DateField()),
                ('Location', models.TextField()),
                ('Category', models.TextField()),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
